# Generated by Django 5.1.2 on 2024-11-11 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d5f5298-fd49-4604-b97f-08b580e64e41'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e021b5b7-f920-4ffa-b6ba-1f12a312e0be'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('new', 'New'), ('used', 'Used')], default='new', max_length=7),
        ),
    ]
