# Generated by Django 5.1.2 on 2024-11-07 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orderpaymentstatus_id_alter_orderstatus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1f20d74-9153-49aa-9901-38cd9d33099d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('adefaa1d-c8f2-4c3b-a273-bef625eaf03b'), primary_key=True, serialize=False),
        ),
    ]
