# Generated by Django 5.1.2 on 2024-11-12 05:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orderpaymentstatus_id_alter_orderstatus_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimension',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='frametype',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e37259ad-883e-4444-808e-1fd5e3aa4acb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ddd7603-ec88-498f-8034-37946957f3f4'), primary_key=True, serialize=False),
        ),
    ]
