# Generated by Django 5.1.2 on 2024-12-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_promocode_status_alter_resetpassword_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleague',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='colleague',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('invalid', 'Invalid'), ('valid', 'Valid')], default='invalid', max_length=7),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('used', 'Used'), ('new', 'New')], default='new', max_length=7),
        ),
    ]
