# Generated by Django 5.1.2 on 2024-12-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_colleague_is_admin_alter_colleague_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleague',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colleague',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('expired', 'Expired')], default='new', max_length=7),
        ),
    ]
