# Generated by Django 5.1.2 on 2024-11-12 09:24

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dimension_unique_together_alter_color_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('value_percentage', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='invalid', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'db_table': 'promocode',
            },
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='frame_type',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items_cost',
            new_name='total_items_cost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items_count',
            new_name='total_items_count',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='total_order_cost',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='cost',
            new_name='item_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitems',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae5e77cd-4dea-45b6-beea-282fcb5784bf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9039b376-8337-4bb6-b293-e75b42da61f2'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payment Info',
                'verbose_name_plural': 'Payment Infos',
                'db_table': 'paymentinfo',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocode'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocode'),
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('delivery_period', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
            options={
                'verbose_name': 'Shipping Info',
                'verbose_name_plural': 'Shipping Infos',
                'db_table': 'shippinginfo',
            },
        ),
        migrations.DeleteModel(
            name='ProductDimensions',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
