# Generated by Django 5.1.2 on 2024-11-07 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderpaymentstatus_id_alter_orderstatus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleague',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78af23f2-7099-4aa1-af21-583329ea899f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1917ccb2-7e9d-4c97-bdc3-f1bbe5cda15e'), primary_key=True, serialize=False),
        ),
    ]
