# Generated by Django 5.1.2 on 2024-11-07 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_colleague_is_staff_alter_orderpaymentstatus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ff647985-443c-4a5f-bc8a-c760a3d5b099'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8aa4d816-176a-497d-af73-a692b2b9f107'), primary_key=True, serialize=False),
        ),
    ]
