# Generated by Django 5.1.2 on 2024-11-08 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orderpaymentstatus_id_alter_orderstatus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('137de4a7-eaaa-474d-930a-d5efcaec926c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21e22b0a-ba6d-4cb1-bec4-b4c8ae21d09f'), primary_key=True, serialize=False),
        ),
    ]
