# Generated by Django 5.1.2 on 2024-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_department_role_remove_colleague_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleague',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='invalid', max_length=7),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('new', 'New'), ('used', 'Used')], default='new', max_length=7),
        ),
    ]
