# Generated by Django 5.1.2 on 2024-12-03 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_staff_id_alter_promocode_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
