# Generated by Django 5.1.2 on 2024-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('expired', 'Expired')], default='new', max_length=7),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
