# Generated by Django 5.1.2 on 2024-11-14 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_promo_code_alter_orderpaymentstatus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b096c83b-661d-4f3b-9755-10c7c5f138c8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53d8cc0c-e332-4a1c-8ca3-7e121040c9f6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('invalid', 'Invalid'), ('valid', 'Valid')], default='invalid', max_length=7),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired'), ('used', 'Used')], default='new', max_length=7),
        ),
    ]
