# Generated by Django 5.1.2 on 2024-11-14 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_orderpaymentstatus_id_alter_orderstatus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8470aa7b-4d1b-448f-a85f-e9a1a6fd12c9'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4045d85-9ebc-4e93-a2dc-48e731bb3d6b'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='invalid', max_length=7),
        ),
    ]
