# Generated by Django 5.1.2 on 2024-11-14 23:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderpaymentstatus_id_alter_orderstatus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c7e622e-6af0-4b07-b400-c2de38b669a8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10fa53e9-276c-483c-9520-35d9db5a1258'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('used', 'Used'), ('new', 'New')], default='new', max_length=7),
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
