# Generated by Django 5.1.2 on 2024-12-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_resetpassword_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('expired', 'Expired')], default='new', max_length=7),
        ),
    ]
