# Generated by Django 5.1.2 on 2024-11-15 00:02

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import helpers.defaults
import helpers.generators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_added_by_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95f4d96e-2b12-4640-b40e-ae7fcc2c07c3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d9280b5-3725-42f3-8693-27cebe0df86e'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, default=helpers.generators.generate_order_number, max_length=255, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_items_count', models.PositiveIntegerField(default=0)),
                ('total_items_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_order_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment_status', models.ForeignKey(default=helpers.defaults.order_payment_status_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.orderpaymentstatus')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocode')),
                ('status', models.ForeignKey(default=helpers.defaults.get_default_order_status, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.orderstatus')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('product_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.product')),
                ('promo_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocode')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'orderitem',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='api.OrderItems', to='api.product'),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentmethod')),
            ],
            options={
                'verbose_name': 'Payment Info',
                'verbose_name_plural': 'Payment Infos',
                'db_table': 'paymentinfo',
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('delivery_period', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='api.order')),
            ],
            options={
                'verbose_name': 'Shipping Info',
                'verbose_name_plural': 'Shipping Infos',
                'db_table': 'shippinginfo',
            },
        ),
    ]
