# Generated by Django 5.1.2 on 2024-11-15 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_orderpaymentstatus_id_alter_orderstatus_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='product_cost',
            new_name='product_order_cost',
        ),
        migrations.AlterField(
            model_name='orderpaymentstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35c10c64-57fe-4998-aea1-344380a37d58'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('179942b8-889e-46e3-97de-77283ea221a8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('invalid', 'Invalid'), ('valid', 'Valid')], default='invalid', max_length=7),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired'), ('used', 'Used')], default='new', max_length=7),
        ),
    ]
