# Generated by Django 5.1.2 on 2024-12-05 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_colleague_full_name_alter_promocode_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationCodeStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colleague',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colleague',
            name='is_account_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='status',
            field=models.CharField(choices=[('invalid', 'Invalid'), ('valid', 'Valid')], default='invalid', max_length=7),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired'), ('used', 'Used')], default='new', max_length=7),
        ),
        migrations.AddField(
            model_name='colleague',
            name='confirmation_code_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.confirmationcodestatus'),
        ),
    ]
